version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "testing..."
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Hellloooo!"
workflows:
  version: 2.1
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
