version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:13.10.1
    steps:
      - checkout
      - run: echo "testing..."
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: circleci/node:13.10.1
    steps:
      - checkout
      - run: echo "Hellloooo!"
workflows:
  version: 2.1
  test_and_lint:
    jobs:
      - hithere
      - test:
          requires:
            - hithere
